name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  image:
    name: Push Container Image
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build images
      run: |
        docker build -t accurate:dev .
    - name: Login to ghcr.io
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push images
      run: |
        TAG=${GITHUB_REF#refs/tags/v}
        docker tag accurate:dev ghcr.io/cybozu-go/accurate:$TAG
        docker push ghcr.io/cybozu-go/accurate:$TAG
  release:
    name: Release on GitHub
    needs: image
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - uses: ./.github/actions/aqua
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set previous release tag for GoReleaser
      run: |
        export TAG=$(curl -s "https://api.github.com/repos/cybozu-go/accurate/releases/latest" | jq -r .tag_name)
        echo "GORELEASER_PREVIOUS_TAG=${TAG}" >> $GITHUB_ENV
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
      with:
        distribution: goreleaser
        version: v2.5.1
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@92da038bbf995803124a8e50ebd438b2f37bbbb0 # v0.0.43
  chart-release:
    runs-on: ubuntu-24.04
    needs: release
    if: contains(needs.release.result, 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v４.2.0
      - name: Set chart version
        run: |
          helm repo add accurate https://cybozu-go.github.io/accurate
          helm repo update
          
          # get the release tag version
          tag_version=${GITHUB_REF##*/v}
          
          # get the latest chart version
          chart_version=$(helm search repo accurate -o json | jq -r 'sort_by(.version) | .[-1].version')
          chart_patch_version=${chart_version##*.}
          new_patch_version=$(($chart_patch_version+1))
          
          # if minor or major version changed, reset new patch version
          local_version=$(cat charts/accurate/Chart.yaml | yq .version | sed "s/0-chart-patch-version-placeholder/$chart_patch_version/g")
          [ "$local_version" != "$chart_version" ] && new_patch_version=0
          
          # replace placeholder with new version
          sed --in-place "s/app-version-placeholder/$tag_version/g" charts/accurate/Chart.yaml
          sed --in-place "s/0-chart-patch-version-placeholder/$new_patch_version/g" charts/accurate/Chart.yaml
          sed --in-place "s/app-version-placeholder/$tag_version/g" charts/accurate/values.yaml
      - name: Create release notes
        run: |
          tag_version=${GITHUB_REF##*/}
          cat <<EOF > ./charts/accurate/RELEASE.md
          Helm chart for accurate [$tag_version](https://github.com/cybozu-go/accurate/releases/tag/$tag_version)
          
          EOF
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
        with:
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
